#!/usr/bin/perl
$ID = $Id$;
#
# lsmounts -- List volumes which have mountpoints in directory.

use Cwd;

my $directory = $ARGV[0] || cwd;
opendir(DIR,$directory) or die "Can't open $directory: $!\n";
while (defined($_ = readdir(DIR))) {
    $_ = "$directory/$_";
    lstat($_);
    if (-d _) {
        $mtpt = `/usr/pubsw/bin/fs lsmount $_ 2>&1`;
        $ismtpt = ($? == 0);
        if ( $ismtpt ) {
            $mtpt =~ s/.*a mount point for volume \'\#(\S+)\'\s+$/$1/ ;
            print $mtpt, "\n";
        }
    }
}
closedir(DIR);
